- name: CI/CD with Docker & Kubernetes (No Roles)
  hosts: docker_k8s
  become: yes
  vars_files:
    - vault.yml

  tasks:
    - name: Copy project files to remote node
      copy:
        src: ../
        dest: /opt/flask-app/
        mode: 0755

    - name: Docker login to Docker Hub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Build and push Docker image
      community.docker.docker_image:
        name: ednvk/flask-app
        tag: latest
        source: build
        build:
          path: /opt/flask-app/
        push: yes
        force_source: true
        force_tag: true

    - name: Deploy to Kubernetes via Minikube
      shell: |
        kubectl apply -f /opt/flask-app/k8s/deployment.yml
        kubectl apply -f /opt/flask-app/k8s/service.yml
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config  # or the correct path from `minikube start` output
      register: k8s_output

